### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/230
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d24c65ca93265e1ea9448d9c9f9ed73af63aae19

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now f20c186db7761e82340dd31bd431cf2ee4c6e432

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
