### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>
Depends-On: https://github.com/ansible/ansible/pull/62596

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ed752af8e6c2a5a2c7b0cd40e0da1a9a3181f7f3

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now e3c171e630750a023af45e5849ead03fb602a1db

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4e1ab482f019bb16ce5bf11a673c98a1bf4eafac

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
