### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible/pull/60947
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now fa1284daa86c222ca5e943362ebc71cfdc308900

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 806cdd5a7af13d2f68da11e13e2d45e12bbc8bf5

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 7c4560deac773c6ca107c34f7189dbcf96fff49a

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c88021186b62b63dd1f927406207a3365e90dcc7

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ff5a376686a2c9df2360c94d4453385f7889edda

**Pull request merged**
